(import "../lib/unit.scm" :as Unit)

(Unit.test "boolean?"
    (Unit.assert-falsy (*builtin*.boolean? ()))
    (Unit.assert-truthy (*builtin*.boolean? #t))
    (Unit.assert-truthy (*builtin*.boolean? #f))
    (Unit.assert-falsy (*builtin*.boolean? #\A))
    (Unit.assert-falsy (*builtin*.boolean? 1))
    (Unit.assert-falsy (*builtin*.boolean? "name"))
    (Unit.assert-falsy (*builtin*.boolean? 'name))
    (Unit.assert-falsy (*builtin*.boolean? :name))
    (Unit.assert-falsy (*builtin*.boolean? '(1 2 3)))
    (Unit.assert-falsy (*builtin*.boolean? []))
    (Unit.assert-falsy (*builtin*.boolean? [1 2 3]))
    (Unit.assert-falsy (*builtin*.boolean? {}))
    (Unit.assert-falsy (*builtin*.boolean? {:a 1 :b 2 :c 3}))
    (Unit.assert-falsy (*builtin*.boolean? (proc (n) (+ n 1))))
    (Unit.assert-falsy (*builtin*.boolean? car))
    (Unit.assert-falsy (*builtin*.boolean? and))
)
