(import "../lib/unit.scm" :as Unit)

(define *builtin* (get (car **root**) :builtins))

(Unit.test "atom?"
    (Unit.assert-falsy (*builtin*.atom? ()))
    (Unit.assert-falsy (*builtin*.atom? 1))
    (Unit.assert-falsy (*builtin*.atom? #\A))
    (Unit.assert-falsy (*builtin*.atom? "name"))
    (Unit.assert-falsy (*builtin*.atom? 'name))
    (Unit.assert-falsy (*builtin*.atom? :name))
    (Unit.assert-falsy (*builtin*.atom? '(1 2 3)))
    (Unit.assert-falsy (*builtin*.atom? []))
    (Unit.assert-falsy (*builtin*.atom? [1 2 3]))
    (Unit.assert-falsy (*builtin*.atom? (*builtin*.byte-vector 1 2 3)))
    (Unit.assert-falsy (*builtin*.atom? {}))
    (Unit.assert-falsy (*builtin*.atom? {:a 1 :b 2 :c 3}))
    (Unit.assert-truthy (*builtin*.atom? (*builtin*.atom 1)))
    (Unit.assert-falsy (*builtin*.atom? (proc (n) (+ n 1))))
    (Unit.assert-falsy (*builtin*.atom? car))
    (Unit.assert-falsy (*builtin*.atom? and))
)
