(const (package-use package name)
    (if (contains? package name) 
        (get package name)
        (raise 'UnknownSymbolInPackage {:name name})
    )
)

(macro (package-import name)
    `(*builtin*.import-source ~name)
)

(macro (import name . options) 
    (if (and (= (first options) :as) (not (nil? ((get *builtin* 'list-nth) options 1))))
        `(const- ~((get *builtin* 'list-nth) options 1) (package-import ~name))
        (raise 'IllegalImportSyntax {:expected ":as symbol"})
    )
)
