(import "./unit.scm" :as Unit)

(Unit.test "number?"
    (Unit.assert-falsy (number? ()))
    (Unit.assert-truthy (number? 1))
    (Unit.assert-falsy (number? "name"))
    (Unit.assert-falsy (number? 'name))
    (Unit.assert-falsy (number? :name))
    (Unit.assert-falsy (number? '(1 2 3)))
    (Unit.assert-falsy (number? []))
    (Unit.assert-falsy (number? [1 2 3]))
    (Unit.assert-falsy (number? {}))
    (Unit.assert-falsy (number? {:a 1 :b 2 :c 3}))
    (Unit.assert-falsy (number? (fn (n) (+ n 1))))
    (Unit.assert-falsy (number? car))
    (Unit.assert-falsy (number? cond))
)

(Unit.test "string?"
    (Unit.assert-falsy (string? ()))
    (Unit.assert-falsy (string? 1))
    (Unit.assert-truthy (string? "name"))
    (Unit.assert-falsy (string? 'name))
    (Unit.assert-falsy (string? :name))
    (Unit.assert-falsy (string? '(1 2 3)))
    (Unit.assert-falsy (string? []))
    (Unit.assert-falsy (string? [1 2 3]))
    (Unit.assert-falsy (string? {}))
    (Unit.assert-falsy (string? {:a 1 :b 2 :c 3}))
    (Unit.assert-falsy (string? (fn (n) (+ n 1))))
    (Unit.assert-falsy (string? car))
    (Unit.assert-falsy (string? cond))
)

(Unit.test "symbol?"
    (Unit.assert-falsy (symbol? ()))
    (Unit.assert-falsy (symbol? 1))
    (Unit.assert-falsy (symbol? "name"))
    (Unit.assert-truthy (symbol? 'name))
    (Unit.assert-falsy (symbol? :name))
    (Unit.assert-falsy (symbol? '(1 2 3)))
    (Unit.assert-falsy (symbol? []))
    (Unit.assert-falsy (symbol? [1 2 3]))
    (Unit.assert-falsy (symbol? {}))
    (Unit.assert-falsy (symbol? {:a 1 :b 2 :c 3}))
    (Unit.assert-falsy (symbol? (fn (n) (+ n 1))))
    (Unit.assert-falsy (symbol? car))
    (Unit.assert-falsy (symbol? cond))
)
