name: Test ilisp

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Check LLVM
      #   run: |
      #     llvm-as-9 --version
      #     clang-9 --version
      #     llvm-link-9 --version
      #     lli-9 --version
      - name: Install readline
        run: |
          sudo apt-get update
          sudo apt-get -y install libedit-dev
      - name: Build and test
        run: |
          export ILISP_PRELUDE=/home/runner/work/ilisp/ilisp/lib/prelude.scm
          make
