name: Test ilisp

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm      
      - name: Check LLVM
        run: |
          llvm-as --version
          clang --version
          llvm-link --version
          lli --version
      - name: Install readline
        run: |
          sudo apt-get update
          sudo apt-get -y install libedit-dev
      - name: Build and test
        run: |
          export ILISP_PRELUDE=/home/runner/work/ilisp/ilisp/lib/prelude.scm
          export MINI_ILISP_LIB=/home/runner/work/ilisp/ilisp/scratch/lib.ll
          make
